### PR TITLE
Adding an ObservableNavigatableCollection that provides the option to…

### PR DESCRIPTION
**Pull request by msftgeek**
… easily navigate the items in the collection.

### CODE REVIEW

**Comment by balivo** [comment]
NuGet updated? Samples?

**Comment by jamesmontemagno** [comment]
I need more definition as to what this feature is, how it is used, and why it should be added. Not enough in the PR.

**Comment by msftgeek** [comment]
This extends an Observable Collection to make it easy to navigate around it such as going to the Start, End or Next, Previous. It's useful for when you are cycling through a collection of images (for example) and need to be able to provide bind controls for moving between the images.

I've found it useful in a few projects that required moving through images and also moving through text passages, such as a collection of jokes in an app.

**Comment by jamesmontemagno** [comment]
I am thinking these could be extension methods to observablerangecollection instead of a class

**Pull request closed without merging**
