### PR TITLE
Added InsertRange

### PR DESCRIPTION
**Pull request by BryanSan**
Insert a collection in the specified index keeping the order of the specified collection

### CODE REVIEW

**Comment by BryanSan** [comment]
I dont know why AppVeyor is failing :((((( heeeeeeeelpppp

**Comment by jamesmontemagno** [comment]
You can see the build logs here:

 ObservableRangeCollection.cs(131,106): error CS0305: Using the generic type 'IList<T>' requires 1 type arguments [C:\projects\mvvm-helpers\MvvmHelpers\MvvmHelpers.csproj]
  ObservableRangeCollection.cs(131,124): error CS1503: Argument 3: cannot convert from 'int' to 'System.Collections.IList' [C:\projects\mvvm-helpers\MvvmHelpers\MvvmHelpers.csproj]
    0 Warning(s)
    2 Error(s)

**Comment by jamesmontemagno** [comment]
There is a lot more error handling that would need to be implemented here such as the index being under or over.

**Comment by weitzhandler** [comment]
@jamesmontemagno 
I can do it.
Can you please first take a look and review/accept my PR? #26

**Comment by jamesmontemagno** [comment]
Closing as out of date

**Pull request closed without merging**
